# Generated by Django 3.1.3 on 2020-11-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCpuRamLoad',
            fields=[
                ('timeid', models.DateTimeField(primary_key=True, serialize=False)),
                ('servername', models.CharField(max_length=5)),
                ('memload', models.FloatField(blank=True, null=True)),
                ('cpuload', models.FloatField(blank=True, null=True)),
                ('sshstatus', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'tb_cpu_ram_load',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDiskCapacity',
            fields=[
                ('timeid', models.DateTimeField(primary_key=True, serialize=False)),
                ('servername', models.CharField(max_length=20)),
                ('filesystem', models.CharField(max_length=50)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('used', models.CharField(blank=True, max_length=20, null=True)),
                ('avail', models.CharField(blank=True, max_length=20, null=True)),
                ('percentageusage', models.IntegerField(blank=True, null=True)),
                ('mounted', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_disk_capacity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbInodesUsage',
            fields=[
                ('timeid', models.DateTimeField(primary_key=True, serialize=False)),
                ('servername', models.CharField(max_length=20)),
                ('filesystem', models.CharField(max_length=50)),
                ('inodestotal', models.IntegerField(blank=True, null=True)),
                ('used', models.IntegerField(blank=True, null=True)),
                ('inodesfree', models.IntegerField(blank=True, null=True)),
                ('percentageiusage', models.IntegerField(blank=True, null=True)),
                ('mounted', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_inodes_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(max_length=20)),
                ('ipaddress', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_server',
                'unique_together': {('id', 'servername')},
            },
        ),
        migrations.CreateModel(
            name='DbReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=20)),
                ('report_name', models.CharField(max_length=20)),
                ('botid', models.CharField(max_length=50)),
                ('groupid', models.IntegerField()),
            ],
            options={
                'db_table': 'db_report',
                'unique_together': {('id', 'report_id', 'botid')},
            },
        ),
    ]
