# Generated by Django 3.1.3 on 2020-11-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmsdash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbreport',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbserver',
            options={'managed': False},
        ),
    ]
